# Site settings
author:
  name: "Chaitanya Kundety"
  email: "chaitanyakun@outlook.com"
title: "Chaitanya Kundety | Portfolio"
email: chaitanyakun@outlook.com
description: "Portfolio website showcasing my projects, education, and skills."
keywords: "chaitanya, kundety, krishna chaitanya, kkc, ckundety, chaitanyakun, machine learning, artificial intelligence, ml, ai, dl, genai, llm, deep learning, mlops, ai engineer, ml engineer, machine learning engineer, data scientist, data engineering, applied machine learning, ml developer, ai developer, computer vision, cv, natural language processing, nlp"
baseurl: ""
url: "https://kkchait.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - docker-compose.yml
  - skillcloud.ipynb

# GitHub settings
github: 
  is_project_page: false

# Configure plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Additional configurations
permalink: /:title/

# Sitemap settings
sitemap:
  changefreq: 'monthly'
  priority: 1.0

# SEO settings
title_separator: "|"
seo:
  type: "website"

# Gtag settings
gtag:
  mid: "G-Z992N89KP1"