version: '3'
services:
  jekyll:
    image: jekyll/jekyll:builder
    command: jekyll serve --watch --force_polling --drafts --verbose
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
